POST http://localhost:8080/rooms
Content-Type: application/json

{
  "roomId": "7ccb3f00-2775-4f21-9ed9-e52e2e36a982",
  "name": "room1"
}

###

GET http://localhost:8080/rooms

###ClientsByEventProcessor

POST http://localhost:8080/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/participants
Content-Type: application/json

{
  "name": "Sara"
}

###

GET http://localhost:62038/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/participants

###

POST http://localhost:8080/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/messages
Content-Type: application/json

{
	"name": "Sara",
	"message": "Ciao Marc"
}

###

GET http://localhost:8080/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/messages

###


POST http://localhost:9090/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/participants
Content-Type: application/json

{
  "name": "Marc"
}

###


POST http://localhost:9090/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/messages
Content-Type: application/json

{
  "name": "Marc",
  "message": "Good afternoon Sara"
}

###

GET http://localhost:9090/rooms/56f85087-64fa-456f-bc2c-d009e6462f35/messages

###


POST http://localhost:8024/actuator/loggers/io.axoniq.axonserver
Content-Type: application/json

{
  "configuredLevel": "DEBUG"
}

###

POST http://localhost:8024/actuator/loggers/io.axoniq.axonhub.grpc.QueryService
Content-Type: application/json

{
  "configuredLevel": "TRACE"
}

###

POST http://localhost:8024/actuator/loggers/io.axoniq.axonserver.cluster.RaftNode
Content-Type: application/json

{
  "configuredLevel": "TRACE"
}

###